version: "3.7"

services:

  api:
    container_name: demoapi_api
    build:
      dockerfile: Dockerfile
      context: ./go/src/demoapi
      args:
        VERSION: "${VERSION:-alpha}"
    env_file:
      - ./.env/db.env
      - ./.env/db.secret.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: demoapi_db
    image: postgres:11
    restart: always
    env_file:
      - ./.env/db.env
      - ./.env/db.secret.env
    ports:
      - "5432:5432"
    volumes: # remove volume to not persist data between containerizations
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
